ezio1119/freemarket_sample_56b

- README.md
> Database 設計

- db/migrate/20190809114713_change_column_to_user.rb
- db/schema.rb
> Userモデルカラム修正

- app/assets/stylesheets/_identification.scss
- app/assets/stylesheets/application.scss
- app/controllers/users_controller.rb
- app/views/users/identification.html.haml
- config/routes.rb
ユーザー本人確認ページを実装する。
ユーザビリティを向上させる為。
> ユーザー本人確認ページの実装

- Dockerfile
- Dockerfile.dev
- Gemfile
- Gemfile.lock
- app/controllers/users_controller.rb
- app/models/address.rb
- app/models/prefecture.rb
- app/models/user.rb
- app/views/users/identification.html.haml
- db/migrate/20190810104621_create_addresses.rb
- db/schema.rb
address.rbの追加
addresstableの追加
#why
ユーザー登録機能に必要なため
> アドレスモデルの追加 add activehash

- app/assets/stylesheets/_identification.scss
- app/views/users/identification.html.haml
- db/schema.rb
ユーザー本人確認ページの編集を行う。
active_hashを使用して都道府県の選択ができるようにする際に、form_forを用いて記述する為。
> ユーザー本人確認ページの編集

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/cards.scss
- app/assets/stylesheets/cards_scss/_cards_index.scss
- app/controllers/cards_controller.rb
- app/views/cards/index.html.haml
- config/routes.rb
- db/schema.rb
ユーザークレジットカード登録ページを実装する。
ユーザビリティを向上させる為。
> ユーザークレジットカード登録ページの実装

- README.md
- app/controllers/items_controller.rb
- app/models/day.rb
- app/models/delivery_burden.rb
- app/models/delivery_method.rb
- app/models/item.rb
- app/models/state.rb
- app/views/items/_item.html.haml
- app/views/items/new.html.haml
- app/views/items/show.html.haml
- config/routes.rb
- db/migrate/20190812083347_rename_column_items.rb
- db/schema.rb
- spec/factories/items.rb
- spec/models/item_spec.rb
商品詳細画面実装。データベースから商品データを取り出し、詳細画面で閲覧できる機能を追加する。
本アプリケーションのユーザビリティを高めるため。
> [WIP]商品詳細画面実装

- app/assets/stylesheets/_logout.scss
- app/assets/stylesheets/application.scss
- app/controllers/users/sessions_controller.rb
- app/controllers/users_controller.rb
- app/views/users/_sidebar.html.haml
- app/views/users/logout.html.haml
- config/routes.rb
ユーザーログアウトページを作成する。
ユーザビリティの向上の為。
> ユーザーログアウトページの実装

- db/migrate/20190816114432_rename_size_column_to_items.rb
- db/schema.rb
#what
Itemsテーブルのsizeカラムをsize_idに変更
#why
activehashを使って静的なデータを保存するため
> change items column size_id

- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.haml
- db/migrate/20190816104142_brands.rb
- spec/factories/categories.rb
- spec/factories/items.rb
passwordをformのvalueに表示させないように修正。
カテゴリーテーブル追加に伴い、新規出品機能の単体テストにカテゴリー追加。
セキュリティ向上のため。
メンテナンス性向上のため。
> omniauth機能、商品単体テスト修正

- app/controllers/items_controller.rb
- app/models/category.rb
- spec/controllers/items_controller_spec.rb
- spec/factories/items.rb
- spec/factories/users.rb
- spec/models/item_spec.rb
- spec/rails_helper.rb
#what
item-modelのテスト
Items-controllerのテスト
#why
バグの早期発見
保守性の向上
> Items-Test

- Dockerfile
- config/database.yml
> Drop database

- app/views/items/search.html.haml
- db/schema.rb
#what
imageの修正
#why
image が配列で保存されていたから
eachで回して解決
> change image

- config/initializers/devise.rb
> Fix omniauth address

- app/views/items/search.html.haml
#what
イメージサイズの変更
#why
ユーザビリティの向上
> change size img

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/items/_item_new.scss
- app/models/item.rb
- app/views/items/new.html.haml
- config/application.rb
- config/locales/ja.yml
- db/schema.rb
#what
Itemのエラーメッセージの表示
#why
ユーザビリティの向上のため
> エラーメッセージの表示(Item)

- app/assets/stylesheets/cards/_cards_index.scss
- app/assets/stylesheets/users/_items_list.scss
- app/views/orders/change.html.haml
- app/views/users/cards/_card.html.haml
- app/views/users/cards/index.html.haml
- app/views/users/cards/new.html.haml
- app/views/users/cards/register.html.haml
カードの登録、削除画面のuiが貧弱だったため修正。
当該ページのhtmlとcssを変更。
> fix-card-ui

- app/assets/stylesheets/items/_item_new.scss
- app/models/item.rb
- app/views/items/new.html.haml
- spec/factories/items.rb
- spec/models/item_spec.rb
#what
itemモデルのテスト
#why
保守性の向上のため
> Item model Rspec

- app/assets/stylesheets/users/_sign_address.scss
- app/controllers/users/addresses_controller.rb
- app/models/address.rb
- app/views/users/addresses/index.html.haml
- config/locales/ja.yml
- db/schema.rb
- docker-compose.yml
エラーメッセージを追加しユーザーにわかりやすくする。」
アドレス登録のエラーメッセージを追加
> アドレス登録のエラーメッセージを追加

- app/assets/javascripts/slider.js
- app/assets/stylesheets/items/_buybtn.scss
- app/assets/stylesheets/items/_item_index.scss
- app/views/items/_slider.html.haml
- app/views/items/index.html.haml
- app/views/layouts/application.html.haml
swiper.jsでトップページにスライダー追加。
デザイン性を向上させるため。
> トップページスライダー追加

- app/assets/stylesheets/users/_sign_address.scss
- app/assets/stylesheets/users/_sign_up_view.scss
- app/controllers/concerns/name_validators.rb
- app/controllers/orders_controller.rb
- app/controllers/users/phone_auth_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/address.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.haml
- app/views/orders/create.html.haml
- app/views/users/addresses/index.html.haml
- app/views/users/cards/new.html.haml
- app/views/users/cards/register.html.haml
- app/views/users/phone_auth/index.html.haml
- app/views/users/phone_auth/send_sms.html.haml
- config/application.rb
- config/locales/ja.yml
ユーザー情報登録のバリデーションとUIを改善。
ユーザー情報登録のエラーメッセージとバリデーションを追加。
ビューのUIも変更。
> ユーザー情報登録のエラーメッセージとバリデーションを追加

- spec/controllers/items_controller_spec.rb
- spec/factories/user.rb
- spec/models/item_spec.rb
#what
Item controller test
#why
保守性の向上のため
> Item controller rspec

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/category/_show.scss
- app/assets/stylesheets/kaminari/_kaminari.scss
- app/controllers/categories_controller.rb
- app/views/categories/index.html.haml
- app/views/categories/show.html.haml
- app/views/kaminari/_first_page.html.haml
- app/views/kaminari/_gap.html.haml
- app/views/kaminari/_last_page.html.haml
- app/views/kaminari/_next_page.html.haml
- app/views/kaminari/_page.html.haml
- app/views/kaminari/_paginator.html.haml
- app/views/kaminari/_prev_page.html.haml
- config/breadcrumbs.rb
- config/locales/kaminari.yml
- config/routes.rb
カテゴリー詳細画面を実装する。カテゴリーごとの商品一覧画面を作成する。
ユーザーが選択したカテゴリーに応じて商品一覧が表示される画面を実装することで、ユーザビリティをさせる為。
> カテゴリー詳細画面の実装2

- app/assets/stylesheets/items/_item_index.scss
- app/views/items/_item.html.haml
- app/views/items/show.html.haml
#what
Item-viewの手直し
#why
ユーザビリティの向上
> Update item view

- app/assets/stylesheets/comments.scss
- app/assets/stylesheets/items/_item_show.scss
- app/controllers/comments_controller.rb
- app/controllers/items_controller.rb
- app/models/comment.rb
- app/models/item.rb
- app/models/user.rb
- app/views/items/show.html.haml
- config/routes.rb
- db/migrate/20190825114546_create_comments.rb
- db/schema.rb
#Whats
コメント機能の実装
#why
ユーザビリティの向上のため
> Coment function

- app/controllers/categories_controller.rb
- app/controllers/concerns/category_items.rb
- app/controllers/items_controller.rb
> fix category

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/items/_item_show.scss
- app/assets/stylesheets/users/_favorites_list.scss
- app/controllers/favorites_controller.rb
- app/controllers/items_controller.rb
- app/controllers/users_controller.rb
- app/models/favorite.rb
- app/models/item.rb
- app/models/user.rb
- app/views/items/_item.html.haml
- app/views/items/show.html.haml
- app/views/users/_sidebar.html.haml
- app/views/users/favorites_list.html.haml
- config/breadcrumbs.rb
- config/routes.rb
- db/migrate/20190826081719_create_favorites.rb
- db/schema.rb
#whay
いいね機能の実装
#why
ユーザビリティの向上のため
> add function to favorite

- app/assets/stylesheets/items/_item_show.scss
- app/assets/stylesheets/items/_search.scss
- app/views/items/search.html.haml
- app/views/items/show.html.haml
soldイメージを追加しわかりやすくする
soldイメージをカテゴリや商品詳細にも記載
> fix soldtag

- app/views/items/show.html.haml
#what
item-showの修正
#why
エラー解決のため
> fix-item-show

- app/assets/javascripts/categories/category-search.js
- app/controllers/comments_controller.rb
- app/views/categories/_category-top.html.haml
- db/schema.rb
#what
categoryにlinkを付与
commentをログインユーザーのみにする
#why
エラー解決のため
> fix category comment

- app/assets/javascripts/item.js
- app/views/devise/registrations/new.html.haml
#what
nameの例を変更
#why
企業様に見せるため
> fix-name-input

- app/assets/javascripts/categories/category-create.js
- app/assets/stylesheets/items/_item_new.scss
- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/new.html.haml
- app/views/items/show.html.haml
#what
itemのnewの手直し
#why
本番での不具合解消
> fix-items-show
